# SPDX-License-Identifier: Apache-2.0

[package]
name = "ws2812"
publish = false
version.workspace = true
edition.workspace = true
description = "WS2812 / SK6812 addressable LED driver"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
api = { path = "../../../api" }
