[package]
name = "esp32-gpio"
version.workspace = true
edition.workspace = true
description = "ESP32 GPIO physical driver"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
flint-hal = { path = "../../../flint-hal" }
flint-arch-xtensa = { path = "../../../arch/flint-arch-xtensa" }
