[package]
name = "esp32-uart"
publish = false
version.workspace = true
edition.workspace = true
description = "ESP32 UART physical driver"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hal = { path = "../../../../hal" }
soc-esp32 = { path = "../../../../soc/esp32" }
