[package]
name = "esp32-spi"
publish = false
version.workspace = true
edition.workspace = true
description = "ESP32 SPI physical driver"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hal = { path = "../../../hal" }
soc-esp32 = { path = "../../../soc/esp32" }
