// SPDX-License-Identifier: Apache-2.0

// ESP32-WROVER Board Manifest
//
// Generated by: cargo generate flint-rtos/template
// Target: ESP32-WROVER

use hal::bus::*;
use soc_esp32::addr;

pub const BOARD_NAME: &str = "ESP32-WROVER";

/// Radios this board's module physically carries.
///
/// A fact about the hardware, in the same way a pin number is — which is why
/// it lives in the manifest rather than being assumed from the SoC family.
/// Every ESP32 part FlintOS supports today has both, but the ESP32-S2 has no
/// Bluetooth at all and would declare `HAS_BT = false`, so applications that
/// ask for a radio the board has not got fail to build instead of failing to
/// connect.
///
/// The kernel checks these against the `radio-*` features; see
/// `kernel/src/radio.rs`.
pub const HAS_WIFI: bool = true;
pub const HAS_BT: bool = true;


/// A GPIO this board holds at a hard, low-impedance high, or `None`.
///
/// The ADC self-test needs one, and the chip cannot supply it: a pad in analog
/// mode has its digital buffers bypassed, and the internal pull-up is tens of
/// kilohms into the SAR's sampling capacitor -- measured at 4% of full scale
/// rather than 80. So the *board* has to provide the high, which makes it a
/// manifest fact rather than something the test can assume.
///
/// A board without one is not broken; the test skips, and says so.
///
/// Nothing on this board holds an ADC1 pin high. As on the DevKitC,
/// GPIO34-39 are input-only with no internal pull.
pub const ADC_EXTERNAL_HIGH_GPIO: Option<u8> = None;

/// A GPIO free for on-chip loopback self-tests (TWAI, I2S). `None` skips them.
/// Left unset: this manifest has never been flashed, so no pin is confirmed
/// free on real hardware.
pub const LOOPBACK_SCRATCH_GPIO: Option<u8> = None;

/// Spare `(a, b)` aux pads for single-pad loopback self-tests. `None` skips
/// them — see the DevKitC manifest for what these are for.
pub const LOOPBACK_AUX_GPIOS: Option<(u8, u8)> = None;

/// Three free pads `[sck, mosi, miso]` for the SPI master↔slave loopback, or
/// `None`. See the DevKitC manifest for what this test does. Left unset: this
/// manifest has never been flashed, so no pin is confirmed free.
pub const SPI_SLAVE_LOOPBACK_GPIOS: Option<[u8; 4]> = None;
/// A free pad for the PCNT self-test. `None` skips it — no pin is confirmed
/// free on real hardware for this unflashed manifest.
pub const PCNT_LOOPBACK_GPIO: Option<u8> = None;

/// No touch-sensor self-test on this board (see the DevKitC manifest).
pub const TOUCH_SELFTEST_GPIO: Option<u8> = None;

/// No MCPWM self-test on this board (see the DevKitC manifest).
pub const MCPWM_SELFTEST_GPIOS: Option<[u8; 3]> = None;


/// Maximum radio transmit power, in dBm.
///
/// A regulatory and thermal choice, not a chip fact, which is why it is a
/// board manifest entry rather than a constant in the radio crate. It feeds
/// the six transmit-power entries of the PHY's initialisation table
/// (`radio_esp32::phy_init`), clamped per modulation exactly as esp-idf's
/// `LIMIT` macro does.
///
/// 20 dBm is esp-idf's own default, and saturates every band. Lower it for a
/// board that runs hot, has a poor antenna, or ships somewhere with a tighter
/// limit than the part can reach.
pub const PHY_MAX_TX_POWER_DBM: i32 = 20;

pub const TICK_PERIOD_US: u32 = 1000;
/// The DMA pool's size is set by the build's memory map (`tools/build/src/map.rs`,
/// radio-keyed against the ROM bound), *not* by this constant, and the runtime
/// reads the real size from the linker symbols the map emits. This value is a
/// manifest fact only: it mirrors the Wi-Fi-only pool the map places (12 KiB; a
/// `radio-bt` build gets 8 KiB, the ROM bound being tighter once the controller
/// takes the bottom of DRAM). See #140.
pub const DMA_POOL_BYTES: usize = 12288;

/// Physical bus drivers to instantiate at boot.
pub const TARGET_BUSES: &[BusMapping] = &[
    BusMapping {
        name: "uart0",
        kind: BusKind::Uart,
        base_addr: addr::UART0_BASE,
        irq: addr::IRQ_UART0,
        dma_capable: true,
        dma_pool_bytes: 512,
        config: BusConfig::uart_8n1(1, 3, 115200),
    },
    BusMapping {
        // VSPI (SPI3). GPIO 23/19/18 are VSPI's IO_MUX-native pins; pairing
        // them with SPI2's base address at 0x3FF64000 -- as this entry used to
        // -- describes a bus that cannot be routed without the GPIO matrix.
        name: "spi3",
        kind: BusKind::Spi,
        base_addr: addr::SPI3_BASE,
        irq: addr::IRQ_SPI3,
        dma_capable: true,
        dma_pool_bytes: 2048,
        config: BusConfig::spi_mode0(23, 19, 18, BusSpeed::MHz(40)),
    },
    BusMapping {
        name: "i2c0",
        kind: BusKind::I2c,
        base_addr: addr::I2C0_BASE,
        irq: addr::IRQ_I2C0,
        dma_capable: false,
        dma_pool_bytes: 0,
        config: BusConfig::i2c(21, 22, BusSpeed::Fast400k),
    },
];

/// Logical device drivers attached to buses.
pub const TARGET_DEVICES: &[BusDevice] = &[
    BusDevice {
        name: "temp_sensor",
        logical_driver: "bme280",
        bus: "spi3",
        cs_pin: Some(15),
        bus_speed: BusSpeed::MHz(4),
    },
    BusDevice {
        name: "display",
        logical_driver: "ssd1306",
        bus: "i2c0",
        cs_pin: None,
        bus_speed: BusSpeed::Fast400k,
    },
];

/// Direct peripheral drivers (not bus-attached).
///
/// UART0 is not repeated here: it is a bus in [`TARGET_BUSES`], and listing it
/// again as a peripheral described one controller twice.
pub const TARGET_PERIPHERALS: &[PeripheralMapping] = &[
    PeripheralMapping { name: "gpio", base_addr: addr::GPIO_BASE, irq: addr::IRQ_GPIO, dma_capable: false, dma_pool_bytes: 0 },
];

/// This board as one value; see [`crate::Board`]. Never flashed, so no free pad
/// is confirmed and `selftest` is all `None`.
pub const BOARD: crate::Board = crate::Board {
    name: BOARD_NAME,
    imu: None,
    pmic: None,
    touch: None,
    display: None,
    rgb_led: None,
    grove: None,
    selftest: crate::SelftestPads {
        scratch: LOOPBACK_SCRATCH_GPIO,
        aux: LOOPBACK_AUX_GPIOS,
        spi_slave: SPI_SLAVE_LOOPBACK_GPIOS,
        pcnt: PCNT_LOOPBACK_GPIO,
        touch: TOUCH_SELFTEST_GPIO,
        mcpwm: MCPWM_SELFTEST_GPIOS,
        adc_external_high: ADC_EXTERNAL_HIGH_GPIO,
    },
    console: crate::ConsolePins { tx: 1, rx: 3, baud: 115_200 },
};
