// SPDX-License-Identifier: Apache-2.0

// ESP32-WROVER Board Manifest
//
// Generated by: cargo generate flint-rtos/template
// Target: ESP32-WROVER

use flint_hal::bus::*;

pub const BOARD_NAME: &str = "ESP32-WROVER";
pub const TICK_PERIOD_US: u32 = 1000;
pub const DMA_POOL_BYTES: usize = 8192;

/// Physical bus drivers to instantiate at boot.
pub const TARGET_BUSES: &[BusMapping] = &[
    BusMapping {
        name: "uart0",
        kind: BusKind::Uart,
        base_addr: 0x3FF40000,
        irq: 34, // ETS_UART0_INTR_SOURCE
        dma_capable: true,
        dma_pool_bytes: 512,
        config: BusConfig::Uart {
            tx: 1,     // GPIO1 (default TX)
            rx: 3,     // GPIO3 (default RX)
            baud: 115200,
            data_bits: UartDataBits::Bits8,
            parity: UartParity::None,
            stop_bits: UartStopBits::Stop1,
        },
    },
    BusMapping {
        // VSPI (SPI3). GPIO 23/19/18 are VSPI's IO_MUX-native pins; pairing
        // them with SPI2's base address at 0x3FF64000 -- as this entry used to
        // -- describes a bus that cannot be routed without the GPIO matrix.
        name: "spi3",
        kind: BusKind::Spi,
        base_addr: 0x3FF65000,
        irq: 31, // ETS_SPI3_INTR_SOURCE
        dma_capable: true,
        dma_pool_bytes: 2048,
        config: BusConfig::Spi {
            mosi: 23,
            miso: 19,
            sck: 18,
            max_speed: BusSpeed::MHz(40),
            mode: SpiMode::Mode0,
        },
    },
    BusMapping {
        name: "i2c0",
        kind: BusKind::I2c,
        base_addr: 0x3FF53000,
        irq: 49, // ETS_I2C_EXT0_INTR_SOURCE
        dma_capable: false,
        dma_pool_bytes: 0,
        config: BusConfig::I2c {
            sda: 21,
            scl: 22,
            speed: BusSpeed::Fast400k,
        },
    },
];

/// Logical device drivers attached to buses.
pub const TARGET_DEVICES: &[BusDevice] = &[
    BusDevice {
        name: "temp_sensor",
        logical_driver: "bme280",
        bus: "spi3",
        cs_pin: Some(15),
        bus_speed: BusSpeed::MHz(4),
    },
    BusDevice {
        name: "display",
        logical_driver: "ssd1306",
        bus: "i2c0",
        cs_pin: None,
        bus_speed: BusSpeed::Fast400k,
    },
];

/// Direct peripheral drivers (not bus-attached).
pub const TARGET_PERIPHERALS: &[PeripheralMapping] = &[
    PeripheralMapping { name: "gpio", base_addr: 0x3FF44000, irq: 22, dma_capable: false, dma_pool_bytes: 0 },
    PeripheralMapping { name: "uart0", base_addr: 0x3FF40000, irq: 34, dma_capable: true, dma_pool_bytes: 512 },
];

/// System service tasks.
pub const TARGET_SERVICES: &[ServiceMapping] = &[
    ServiceMapping { name: "devfs", always: true },
    ServiceMapping { name: "procfs", always: false },
    ServiceMapping { name: "debug", always: false },
];
