[package]
name = "flint-arch-xtensa"
version.workspace = true
edition.workspace = true
description = "Xtensa LX6 HAL implementation for Flint RTOS (ESP32 family)"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
flint-hal = { path = "../../flint-hal" }

[features]
default = []
