# SPDX-License-Identifier: Apache-2.0

[package]
name = "esp32-ledc"
publish = false
version.workspace = true
edition.workspace = true
description = "ESP32 LEDC physical driver — PWM output"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hal = { path = "../../../../hal" }
soc-esp32 = { path = "../../../../soc/esp32" }
