# SPDX-License-Identifier: Apache-2.0

[package]
name = "rp2040-entropy"
publish = false
version.workspace = true
edition.workspace = true
description = "Conditioned best-effort RP2040 ROSC entropy seed"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hal = { path = "../../../../hal" }
soc-rp2040 = { path = "../../../../soc/rp2040" }
