[package]
name = "api"
publish = false
version.workspace = true
edition.workspace = true
description = "FlintOS public API crate — flint::task, flint::queue, flint::mutex, flint::timer, flint::log"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hal = { path = "../hal" }
portable-atomic = { version = "=1.15.0", features = ["critical-section", "require-cas"] }

[features]
default = []
debug-level-0 = []
debug-level-1 = ["flint-log", "flint-metrics", "flint-panic"]
debug-level-2 = ["debug-level-1", "flint-trace"]
debug-level-3 = ["debug-level-2", "flint-timing", "flint-cpu-util"]

flint-log = []
flint-metrics = []
flint-panic = []
flint-trace = []
flint-timing = []
flint-cpu-util = []
